#!/usr/bin/env python3

# Author: Ashley Ferraro
# File: convert.py
# Date: 2/15/2020
# Description: This file converts the text files generated by the serial monitor to csv files

import csv
import os
import sys

rawFileLocation = os.path.dirname(os.path.realpath(sys.argv[1])) + "/"
rawFileLocation += str(sys.argv[1])

newDirectory = rawFileLocation

if newDirectory.endswith('.txt'):
    newDirectory = newDirectory[:-4]

os.mkdir(newDirectory)

OSM = open(newDirectory + "/OSM.txt", 'w+')
SIM = open(newDirectory + "/SIM.txt", 'w+')
RIM = open(newDirectory + "/RIM.txt", 'w+')

print(rawFileLocation)

#rawFile = open(rawFile, 'r')

#with open(rawFileLocation, 'r') as rawFile:

#    for line in rawFile:

#        print(rawFile.readline())

open

currentMode = "OSM"

with open(rawFileLocation, 'r') as rawFile:

    while True:

        line = rawFile.readline()

        if not line:

            break

        line = str(line.strip())

        if(line == "OSM"):

            currentMode = "OSM"
        
        elif(line == "SIM"):

            currentMode = "SIM"

        elif(line == "RIM"):

            currentMode = "RIM"

        if(currentMode == "OSM"): 

            OSM.write(line)

        elif(currentMode == "SIM"):

            SIM.write(line)

        elif(currentMode == "RIM"):

            RIM.write(line)




#with open(d, 'w', newline='') as csvfile:
#    spamwriter = csv.writer(csvfile, delimiter=' ',
#                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
#    spamwriter.writerow(['Spam'] * 5 + ['Baked Beans'])
#    spamwriter.writerow(['Spam', 'Lovely Spam', 'Wonderful Spam'])

