#!/usr/bin/env python3

# Author: Ashley Ferraro
# File: convert.py
# Date: 2/15/2020
# Description: This file converts the text files generated by the serial monitor to csv files

import csv
import os
import datetime
import sys
from os import walk

#rawFileLocation = os.path.dirname(os.path.realpath(sys.argv[1])) + "/"


#add second COMMAND LINE INPUT FROM SCRIPT OF HOW MANY STRIPS INSIDE
#MARK IT AS HOW MANY STRIPS YOU HAVE ON THE TABLE
# 0 means 21 strips
# -1 means 20 strips etc. 



#Gets the current directory that the file is in
currentDirectory = os.getcwd()

listofDir = []
for (dirpath, dirnames, filenames) in walk(currentDirectory):
    listofDir.extend(dirnames)
    break

listofDir.sort(key=os.path.getmtime)

print(listofDir)

rawFileLocation = str(sys.argv[4]) 

print("")
print("Convert arguements")
print("arg[0]: " + str(sys.argv[0]))
print("arg[1]: " + str(sys.argv[1]))
print("arg[2]: " + str(sys.argv[2]))
print("arg[3]: " + str(sys.argv[3]))
print("arg[4]: " + str(sys.argv[4]))


tableDirLocation = str(sys.argv[4]) + "/tables/" + str(listofDir[len(listofDir) - 1]) + "/"

print(rawFileLocation)


rawFileLocation += "/experiments/" + str(sys.argv[1])

stripsRemovedNumber = str(sys.argv[2])

#tableDirLocation +=  str(sys.argv[3]) + "/" 

currentDate = datetime.datetime.now()

newDirectory = tableDirLocation + "measurement-" + str(currentDate.month) + "-" + str(currentDate.day) + "-" + str(currentDate.year) + "-@-" + str(currentDate.hour) + "-" + str(currentDate.minute) + "-" + str(currentDate.second)

#if newDirectory.endswith('.txt'):
#   newDirectory = newDirectory[:-4]
os.mkdir(newDirectory)

OSM = open(newDirectory + "/OSM.csv", 'w+')
SIM = open(newDirectory + "/SIM.csv", 'w+')
RIM = open(newDirectory + "/RIM.csv", 'w+')

#rawFile = open(rawFile, 'r')

#with open(rawFileLocation, 'r') as rawFile:

#    for line in rawFile:

#        print(rawFile.readline())

# open

currentMode = "NONE"

with open(rawFileLocation, 'r') as rawFile:

    while True:

        line = rawFile.readline()

        if not line:

            break

        line = str(line.strip())

        if(line == "OSM"):

            currentMode = "OSM"
        
        elif(line == "SIM"):

            currentMode = "SIM"

        elif(line == "RIM"):

            currentMode = "RIM"

        if(currentMode == "OSM"): 

            if(line != "OSM"):

                OSM.write(line + "," + stripsRemovedNumber + "\n")
      
        elif(currentMode == "SIM"):

            if(line != "SIM"): 

                SIM.write(line + "," + stripsRemovedNumber + "\n")

        elif(currentMode == "RIM"):

            if(line != "RIM"):

                RIM.write(line + "," + stripsRemovedNumber + "\n")





#with open(d, 'w', newline='') as csvfile:
#    spamwriter = csv.writer(csvfile, delimiter=' ',
#                            quotechar='|', quoting=csv.QUOTE_MINIMAL)
#    spamwriter.writerow(['Spam'] * 5 + ['Baked Beans'])
#    spamwriter.writerow(['Spam', 'Lovely Spam', 'Wonderful Spam'])

